import Head from "next/head";

import { useComment } from "src/hooks/useComment";
import { PostTitleByComment } from "src/components/Post/PostTitleByComment";
import { data } from "autoprefixer";

export const Comment = () => {
  const { comment, error, isLoading } = useComment();

  if (isLoading) {
    return(
      <div>ローディング中です。</div>
    );
  }

  if (error) {
    return(
      <div>{error.message}</div>
    );
  }

  return (
    <div>
      <Head>
        <title>{comment?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-lg">
        {comment?.name} ({comment?.email})
      </div>
      <h1 className="text-3xl font-bold">{comment?.body}</h1>
      <div className="mt-2">
        <PostTitleByComment postId={comment.postId} />
      </div>
    </div>
  );
}