import { useState, useCallback, useEffect } from "react";
import Head from "next/head";

import classes from "src/styles/Home.module.css";
import { Header } from "src/components/Header";

const Home = (props) => {
  const [posts, setPosts] = useState([]);

  const getPosts = useCallback(async () => {
    const res = await fetch("https://jsonplaceholder.typicode.com/posts");
    const json =  await res.json();
    setPosts(json);
  }, []);

  useEffect(() => {
    getPosts();
  }, [getPosts])

  return (
    <div className={classes.container}>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ol>
        {
          posts.length > 0 ?
          (
            posts.map((post) => {
              return(
                <li key={post.id}>
                  <h2>{post.title}</h2>
                  <p>{post.body}</p>
                </li>
              );
            })
          ) : null
        }
      </ol>
    </div>
  );
}

export default Home;