import Head from "next/head";

import { Header } from "src/components/Header";
import { Users as UsersComponent } from "src/components/Users/";

const Users = () => {
  return(
    <div>
      <Head>
        <title>Users Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <UsersComponent />
    </div>
  );
}

export default Users;