import Head from "next/head";
import { SWRConfig } from "swr";

import { BASE_ENDPOINT } from 'src/utils/const';
import { Header } from "src/components/Header";
import { UserList } from "src/components/User/UserList";

export const getServerSideProps = async () => {
  const USERS_API_URL = `${BASE_ENDPOINT}/users`;
  const users = await fetch(USERS_API_URL);
  const usersData = await users.json();

  return {
    props: {
      fallback: {
        [USERS_API_URL]: usersData
      }
    }
  }
}

const Users = (props) => {
  const { fallback } = props;

  return(
    <div>
      <Head>
        <title>Users Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SWRConfig value={{fallback}}>
        <Header />
        <UserList />
      </SWRConfig>
    </div>
  );
}

export default Users;
