import Head from "next/head";
import { SWRConfig } from 'swr';

import { BASE_ENDPOINT } from 'src/utils/const';
import { Header } from "src/components/Header";
import { Comments as CommentsComponent } from "src/components/Comments"

export const getStaticProps = async () => {
  const COMMENTS_API_URL = `${BASE_ENDPOINT}/comments`;
  console.log("SGのページ");
  const comments = await fetch(COMMENTS_API_URL);
  const commentsData = await comments.json();

  return {
    props: {
      fallback: {
        [COMMENTS_API_URL]: commentsData
      }
    },
    revalidate: 10
  }
}

const Comments = (props) => {
  const { fallback } = props;

  return(
    <div>
      <Head>
        <title>Users Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SWRConfig value={{fallback}}>
        <Header />
        <CommentsComponent />
      </SWRConfig>
    </div>
  );
}

export default Comments;
